config/routes.rb
Rails.application.routes.draw do

  get 'about' => 'welcome#about'

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

  authenticated :user do
    root :to => 'users#show', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was created successfully."
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "Error creating item.  Please try again."
      redirect_to user_path(current_user)
    end    
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was successfully deleted."
    else
      flash[:alert] = "Error occurred while deleting item.  Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@user, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>
  <%= f.submit "Save", class: 'btn laker' %>
<% end %>

app/views/items/_item.html.erb
<div id=<%= "item-#{item.id}" %> class='row'>
  <div class='col-md-1 time-remaining'>
    <%= distance_of_time_in_words(item.created_at + 7.days - Time.now) %> remaining
  </div>
  <div class='col-md-1 check'>
    <%= link_to "", user_item_path(@user.id, item.id), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
  </div>
  <div class='col-md-8'>
    <h3><%= item.name %></h3>
  </div>
</div>

app/views/items/destroy.js.erb
$('#item-<%= @item.id %>').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocitoff", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<div class="row">
  <div class="col-md-8">
    <% if current_user == @user %>
      <%= render partial: 'items/form' %>
    <% end %>
  </div>
</div>
<% @items.each do |item| %>
  <%= render partial: 'items/item', locals: { item: item } %>
<% end %>

app/views/welcome/about.html.erb
<h1>Blocitoff</h1>
<p>A Bloc project by jd king</p>

app/views/welcome/index.html.erb
<h1>Blocitoff</h1>
<p>A self destructing to-do list application</p>